var indonesiaLang = {
  "getting": "Mulai",
  "please_enter_pin": "Masukan PIN",
  "instruction": "Tekan untuk melihat instruksi",
  "register": "Daftarkan Perangkat menggunakan AuthKey teks",
  "register_": "DAFTARKAN PERANGKAT",
  "instruction_": "Instruksi",
  "manual_auth_key": "Masukkan AuthKey anda",
  "next": "Selanjutnya",
  "validation_authkey1": "Harap masukkan beberapa teks",
  "validation_authkey2": "Silahkan isi teks dengan format yang benar",
  "create_pin1": "Ingat PIN Anda !",
  "create_pin2": "Perlindungan Ekstra dengan PIN DEVICE",
  "create_pin3": "Perangkat Izin Akses Tunggal",
  "create_pin4": "Tidak cocok dengan PIN DEVICE",
  "create_pin5": "Konfirmasi",
  "submit": "Kirim",
  "create_pin6": "Buat PIN",
  "create_pin7": "Konfirmasi PIN",
  "error_create_pin": "*Silakan isi semua sel dengan benar",
  "error_pin_not_same": "*Pin yang anda masukan tidak sama",
  "scan_auth_key": "Pindai Auth Key",
  "enter_auth_key": "Masukkan Auth Key",
  "or": "ATAU",
  "click_here_to_register": "KLIK DI SINI UNTUK DAFTAR",
  "more_instruction": "INSTRUKSI \nLEBIH LANJUT",
  "urgent": "PENTING !",
  "transfer": "Kirim Dana",
  "topup": "Deposit",
  "withdraw": "Penarikan",
  "exchange": "Exchange",
  "receive": "Dana Masuk",
  "last_transactions": "5 Transaksi Terakhir",
  "tips_tricks": "TIPS & TRIK",
  "balance": "Balance",
  "load_more": "Muat lebih banyak...",
  "fee_mode": "Fee Mode",
  "from": "Dari",
  "to": "Ke",
  "currency": "Mata Uang",
  "amount": "Jumlah",
  "note": "Keterangan",
  "confirmation": "Konfirmasi",
  "form": "Form",
  "finished": "Selesai",
  "fee": "Fee",
  "total_sender": "Total Pengirim",
  "total_recipient": "Total Penerima",
  "reference_number": "Nomor Referensi",
  "fasapay_waning":
      "FASAPAY TIDAK BERTANGGUNG JAWAB TERHADAP KERUGIAN APAPUN AKIBAT KESALAHAN PENGINPUTAN DATA.",
  "check_warning":
      "Sudah membaca dengan teliti dan menyatakan bahwa data diatas sudah benar.",
  "need_help": "Butuh Bantuan!",
  "sign_up": "Daftar",
  "title_alert": "Peringatan",
  "message_alert": "Anda yakin ingin menutup aplikasi",
  "no": "Tidak",
  "yes": "Iya",
  "close": "Tutup",
  "enter_your_pin": "Masukan PIN Anda",
  "news": "Berita",
  "read_more": "Baca lebih banyak...",
  "notifikasi": "Notifikasi",
  "search": "Cari",
  "transaction_details": "Detail Transaksi",
  "batchnumber": "Batchnumber",
  "transfer_success": "Transfer Berhasil",
  "transfer_pending": "Transfer Pending",
  "transfer_failed": "Transfer Gagal",
  "topup_success": "Deposit Berhasil",
  "topup_pending": "Deposit Pending",
  "topup_failed": "Deposit Gagal",
  "withdrawal_success": "Penarikan Berhasil",
  "withdrawal_pending": "Penarikan Pending",
  "withdrawal_failed": "Penarikan Gagal",
  "finish": "Selesai",
  "total": "Total",
  "datetime": "Tanggal/Waktu",
  "add_note": "tambahkan catatan (opsional)",
  "transfer_details": "Rincian Transfer",
  "transaction_pin": "PIN Transaksi",
  "welcome": "Selamat Datang",
  "message_qr": "QR Code yang anda scan bukan dari fasapay.",
  "message_info_status_register":
      "Silakan Unggah Identitas Anda untuk mengakses fasilitas ini.",
  "type": "Tipe",
  "transfer_in": "Dana Masuk",
  "transfer_out": "Dana Keluar",
  "message_network_error": "Terjadi masalah pada jaringan",
  "reset": "Muat Ulang",
  "change_language": "Ganti Bahasa",
  "sign_out": "Keluar",
  "profile": "Profil",
  "all": "Semua",
  "top_up": "Deposit",
  "redeem": "Penarikan",
  "cant_be_empty": "Tidak bisa kosong",
  "invalid_email": "Email tidak valid",
  "invalid_phone_number": "Nomor telepon tidak valid",
  "name": "Nama",
  "email": "Email",
  "phone_number": "Nomor Telepon",
  "fullname": "Nama Lengkap",
  "firstname_placeholder": "Nama depan",
  "lastname_placeholder": "Nama belakang",
  "name_placeholder": "Masukkan nama depan dan belakang Anda",
  "email_placeholder": "Masukkan alamat email Anda",
  "phone_number_placeholder": "Masukkan nomor telepon Anda",
  "invalid_auth_key": "Auth key anda tidak valid",
  "verification_email": "Verifikasi Email",
  "verification_code": "Kode Verifikasi",
  "hint_verification_code": "Masukkan kode verifikasi Anda",
  "message_cek_email":
      "Silakan periksa email Anda untuk mendapatkan Kode Verifikasi",
  "thank_you": "Terima kasih",
  "password": "Kata sandi",
  "confirm_password": "Konfirmasi Kata Sandi",
  "security_question": "Pertanyaan Keamanan",
  "security_answer": "Jawaban Keamanan",
  "country": "Negara",
  "address": "Alamat",
  "city": "Kota",
  "postal_code": "Kode Pos",
  "province": "Provinsi",
  "birth_place": "Tempat Lahir",
  "date_of_birth": "Tanggal Lahir",
  "hint_text": "Masukkan %s Anda",
  "terms_and_conditions": "Syarat dan Ketentuan",
  "i_agree_with": "Saya telah membaca dan menyetujui ",
  "privacy_and_policy": "Privasi dan Kebijakan",
  "terms_of_use": "Syarat Penggunaan",
  "and": " dan ",
  "back": "Kembali",
  "agree": "Setuju",
  "disagree": "Tidak Setuju",
  "settings": "Pengaturan",
  "personal_data": "Data Pribadi",
  "batchnumber_copy": "Batchnumber telah disalin",
  "batchnumber_instruction":
      "Sertakan Batchnumber dalam deskripsi saat mentransfer dana.",
  "transfer_following_banks": "Transfer ke salah satu Bank berikut :",
  "transfer_with_bank": "Transfer dengan bank :",
  "choose_bank": "-Pilih Bank-",
  "is_required": "Tidak Boleh Kosong",
  "add_funds": "Tambah Dana",
  "withdraw_funds": "Tarik Dana",
  "member_bank": "Bank Anggota",
  "bank_account_number": "Nomor Rekening Bank",
  "confirmation_form": "Formulir Konfirmasi",
  "bank_ref_code": "Kode Referensi Bank",
  "bank": "Bank",
  "bank_account": "Rekening Bank",
  "deactivate": "Non aktifkan",
  "activate": "Aktifkan",
  "update": "Ubah",
  "add_bank_account": "Tambah Rekening Bank",
  "enter_bank_name": "Masukkan Nama Bank",
  "enter_your_bank_account": "Masukkan Rekening Bank Anda",
  "save": "Simpan",
  "pay_amount": "Jumlah Bayar",
  "home": "Home",
  "history": "History",
  "bank_transfer": "Bank Transfer",
  "master_changer": "Master Changer",
  "exchanger": "Exchanger",
  "payment_gateway": "Payment Gateway",
  "voucher": "Voucher",
  "exchange_rate": "Exchange Rate",
  "error_message_amount": "Tidak boleh @text dari @amount",
  "lebih": "lebih",
  "less": "kurang",
  "swift_code": "Swift Code",
  "bsb_code": "BSB Code",
  "direct_master_changer": "Direct Master Changer",
  "gudang_voucher": "Gudang Voucher",
  "guide": "Panduan",
  "available_only_for_malaysian": "Hanya tersedia untuk Malaysia",
  "other_bank": "Bank Lain",
  "choice_bank_limited": "Choice Bank Limited",
  "united_overseas_bank_limited": "United Overseas Bank Limited",
  "OCBC_singapore": "OCBC Singapore",
  "westpac_banking_corporation": "WestPac Banking Corporation",
  "paid_before": "Dibayar sebelum %s",
  'english': 'Bahasa Inggris',
  'indonesia': 'Indonesia',
  'malaysia': 'Malaysia',
  'korea': 'Korea',
  'rusia': 'Rusia',
  'security_center': 'Pusat Keamanan',
  'security_settings': 'Pengaturan Keamanan',
  'set_and_change_password': 'Setel dan ubah kata sandi',
  'topup_guide': 'Topup Guide',
  'redeem_guide': 'Redeem Guide',
  'ref_code': 'Kode Referensi',
  'reload': 'Muat ulang',
  'transferred_to': 'Ditransfer Ke',
  'withdrawal_process_message':
      'Proses penarikan dapat dilayani dalam waktu 2x24 jam',
  'profil': 'Profil',
  'account_name': 'Nama Akun',
  'change_password': 'Ubah Kata Sandi',
  'change_your_password': 'Ubah kata sandi Anda',
  'change_master_code': 'Ubah Kode Master',
  'change_digit_verification_code': 'Ubah kode verifikasi 6 digit',
  'pin_settings': 'Setelan PIN',
  'change_pin_number': 'Ubah nomor PIN',
};
