var usaLang = {
  "getting": "Start",
  "please_enter_pin": "Please enter pin",
  "instruction": "Tap to see instruction",
  "register": "register device with Auth Key text",
  "register_": "register device",
  "instruction_": "Instruction",
  "manual_auth_key": "Input your Auth Key",
  "next": "Next",
  "validation_authkey1": "Please enter some text",
  "validation_authkey2": "Please fill text with right format",
  "create_pin1": "Remember your pin !",
  "create_pin2": "Extra Protection with pin device",
  "create_pin3": "Single Access Permission device",
  "create_pin4": "Cannot match with pin device",
  "create_pin5": "Confirm",
  "submit": "Submit",
  "create_pin6": "Create pin",
  "create_pin7": "Confirm pin",
  "error_create_pin": "*Please fill up all the cells properly",
  "error_pin_not_same": "*The pin you entered is not the same",
  "scan_auth_key": "Scan for Auth Key",
  "enter_auth_key": "Input Auth Key",
  "or": "OR",
  "click_here_to_register": "CLICK HERE TO REGISTER",
  "more_instruction": "MORE \n INSTRUCTION",
  "urgent": "URGENT !",
  "transfer": "Transfer",
  "topup": "Top Up",
  "withdraw": "Redeem",
  "exchange": "Exchange",
  "receive": "Receive",
  "last_transactions": "Last 5 Transactions",
  "tips_tricks": "TIPS & TRICKS",
  "balance": "Balance",
  "load_more": "Load More...",
  "fee_mode": "Fee Mode",
  "from": "From",
  "to": "To",
  "currency": "Currency",
  "amount": "Amount",
  "note": "Note",
  "confirmation": "Confirmation",
  "form": "Form",
  "finished": "Finished",
  "fee": "Fee",
  "total_sender": "Total Sender",
  "total_recipient": "Total Recipient",
  "reference_number": "Reference Number",
  "fasapay_waning":
      "FASAPAY IS NOT RESPONSIBLE FOR ANY DAMAGE DUE TO DATA ENTRY ERRORS.",
  "check_warning":
      "Have read carefully and declare that the above data is correct.",
  "need_help": "Need Help!",
  "sign_up": "Sign Up",
  "title_alert": "Warnning",
  "message_alert": "Do you want to exit an App",
  "no": "No",
  "yes": "Yes",
  "close": "Close",
  "enter_your_pin": "Enter Your pin",
  "news": "News",
  "read_more": "Read more...",
  "notifikasi": "Notifications",
  "search": "Search",
  "transaction_details": "Transaction Details",
  "batchnumber": "Batchnumber",
  "transfer_success": "Transfer Success",
  "transfer_pending": "Transfer Pending",
  "transfer_failed": "Transfer Failed",
  "topup_success": "Topup Success",
  "topup_pending": "Topup Pending",
  "topup_failed": "Topup Failed",
  "withdrawal_success": "Redeem Success",
  "withdrawal_pending": "Redeem Pending",
  "withdrawal_failed": "Redeem Failed",
  "finish": "Finish",
  "total": "Total",
  "datetime": "Date/Time",
  "add_note": "add note (optional)",
  "transfer_details": "Transfer Details",
  "transaction_pin": "Transaction pin",
  "welcome": "Welcome",
  "message_qr": "The QR Code that you scan is not from Fasapay.",
  "message_info_status_register":
      "Please Upload your Identity to access this facility.",
  "type": "Type",
  "transfer_in": "Transfer In",
  "transfer_out": "Transfer Out",
  "message_network_error": "There is a problem with the network",
  "reset": "Reset",
  "change_language": "Change Language",
  "sign_out": "Sign Out",
  "profile": "Profile",
  "all": "All",
  "top_up": "Top Up",
  "redeem": "Redeem",
  "cant_be_empty": "Can't be empty",
  "invalid_email": "Invalid Email",
  "invalid_phone_number": "Invalid phone number",
  "name": "Name",
  "email": "Email",
  "phone_number": "Phone Number",
  "fullname": "Fullname",
  "firstname_placeholder": "Enter first name",
  "lastname_placeholder": "Enter last name",
  "name_placeholder": "Enter your first and last name",
  "email_placeholder": "Enter your Email address",
  "phone_number_placeholder": "Enter your phone number",
  "invalid_auth_key": "Your auth key is not valid",
  "verification_email": "Verification Email",
  "verification_code": "Verification Code",
  "hint_verification_code": "Enter your verification code",
  "message_cek_email": "Please check your e-mail to get the Verification Code",
  "thank_you": "Thank You",
  "password": "Password",
  "confirm_password": "Confirm Password",
  "security_question": "Security Question",
  "security_answer": "Security Answer",
  "country": "Country",
  "address": "Address",
  "city": "City",
  "postal_code": "Postal Code",
  "province": "Province",
  "birth_place": "Birth Place",
  "date_of_birth": "Date of Birth",
  "hint_text": "Enter Your %s",

// Batas untuk Translate 1

  "terms_and_conditions": "Terms and Conditions",
  "i_agree_with": "I have read  and agree to the ",
  "privacy_and_policy": "Privacy and Policy",
  "and": " and ",
  "terms_of_use": "Terms of Use",
  "back": "Back",
  "agree": "Agree",
  "disagree": "Disagree",
  "settings": "Settings",
  "personal_data": "Personal Data",
  "batchnumber_copy": "Batchnumber has been copied",
  "batchnumber_instruction":
      "Include the Batchnumber in the description when transfering funds.",
  "transfer_following_banks": "Transfer to one of the following Banks :",
  "transfer_with_bank": "Transfer with bank :",
  "choose_bank": "-Choose Bank-",
  "is_required": "Is Required",
  "add_funds": "Add Funds",
  "withdraw_funds": "Withdraw Funds",
  "member_bank": "Member's Bank",
  "bank_account_number": "Bank Account Number",
  "confirmation_form": "Confirmation Form",
  "bank_ref_code": "Bank Ref Code",
  "bank": "Bank",
  "bank_account": "Bank Account",
  "deactivate": "Deactivate",
  "activate": "Activate",
  "update": "Update",
  "add_bank_account": "Add Bank Account",
  "enter_bank_name": "Enter Bank Name",
  "enter_your_bank_account": "Enter Your Bank Account",
  "save": "Save",
  "pay_amount": "Pay Amount",

  "home": "Home",
  "history": "History",
  "bank_transfer": "Bank Transfer",
  "master_changer": "Master Changer",
  "exchanger": "Exchanger",
  "payment_gateway": "Payment Gateway",
  "voucher": "Voucher",
  "exchange_rate": "Exchange Rate",
  "error_message_amount": "Cannot be @text than @amount",
  "more": "more",
  "less": "less",
  "swift_code": "Swift Code",
  "bsb_code": "BSB Code",
  "direct_master_changer": "Direct Master Changer",
  "gudang_voucher": "Gudang Voucher",
  "guide": "Guide",
  "available_only_for_malaysian": "Available only for Malaysian",
  "other_bank": "Other Bank",
  "choice_bank_limited": "Choice Bank Limited",
  "united_overseas_bank_limited": "United Overseas Bank Limited",
  "OCBC_singapore": "OCBC Singapore",
  "westpac_banking_corporation": "WestPac Banking Corporation",
  "paid_before": "Paid before %s",
  'english': 'English',
  'indonesia': 'Indonesia',
  'malaysia': 'Malaysia',
  'korea': 'Korea',
  'rusia': 'Rusia',
  'security_center': 'Security Center',
  'security_settings': 'Security Settings',
  'set_and_change_password': 'Set and change password',
  'topup_guide': 'Topup Guide',
  'redeem_guide': 'Redeem Guide',
  'ref_code': 'Ref Code',
  'reload': 'Reload',
  'transferred_to': 'Transferred To',
  'withdrawal_process_message':
      'Withdrawal process can be served within 2x24 hours',
  'profil': 'Profil',
  'account_name': 'Account Name',
  'change_password': 'Change Password',
  'change_your_password': 'Change your password',
  'change_master_code': 'Change Master Code',
  'change_digit_verification_code': 'Change 6 digit verification code',
  'pin_settings': 'PIN Settings',
  'change_pin_number': 'Change PIN number',
};

// "msg_named": "@name is written in the @email language",
// 'msg_named'.trParams({ 'name': 'Jhon', 'email': 'jhon@example.com' })